project:
  type: website
  output-dir: docs

website:
  title: "Yiran Hu"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
      - text: Resume
        href: resume.qmd

format:
  html:
    theme: cosmo
    toc: true
